services:
  # Servicio para la aplicación Spring Boot
  springboot-app:
    build: .
    container_name: springboot-app
    ports:
      - "8080:8080"  # Puerto para la aplicación
      - "80:80"      # Puerto para Apache
      - "21:21"      # Puerto para FTP
    networks:
      - app-network
    environment:
      # Configuración de memoria JVM para la aplicación
      - JAVA_OPTS=-Xms512m -Xmx1024m
      # Variables de entorno adicionales para conectar a MySQL
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/proyecto_auditoria
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=userpassword
    volumes:
      - ./flags:/flags  # Montar la carpeta de flags
    restart: unless-stopped
    depends_on:
      - mysql-db  # Asegura que MySQL esté listo antes de iniciar la app

  # Servicio para la base de datos MySQL
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3306:3306"  # Puerto para acceso a la base de datos
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: proyecto_auditoria
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - db_data:/var/lib/mysql  # Persistencia de datos
    networks:
      - app-network
    restart: unless-stopped

  # Servicio FTP
  ftp-server:
    image: fauria/vsftpd
    container_name: ftp-server
    ports:
      - "20:20"  # Puerto de datos FTP
      - "21:21"  # Puerto FTP principal
    volumes:
      - ./ftp:/home/vsftpd  # Carpeta para FTP
    environment:
      # Configuración básica para el servidor FTP
      - FTP_USER=user1
      - FTP_PASS=ftp_password
    networks:
      - app-network
    restart: unless-stopped

volumes:
  db_data: {}  # Volumen persistente para MySQL

networks:
  app-network:
    driver: bridge
