services:
  # Servicio para la aplicaci贸n Spring Boot
  springboot-app:
    build: .
    container_name: springboot-app
    ports:
      - "8080:8080" # Puerto para la aplicaci贸n
      - "21:21" # Puerto para FTP
      - "5432:5432" #Puerto para PostgreSQL
      - "10000-10100:10000-10100"
    networks:
      - app-network
    environment:
      # Configuraci贸n de memoria JVM para la aplicaci贸n
      - JAVA_OPTS=-Xms512m -Xmx1024m
    restart: unless-stopped

volumes:
  postgres_data: {} # Volumen persistente para MySQL

networks:
  app-network:
    driver: bridge
